deply final v5

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -361,11 +361,12 @@ jobs:
           name: Frontend smoke test.
           command: |
             FRONTEND-WEBSITE="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"
-            if curl -s $FRONTEND-WEBSITE | grep "Welcome"
+            echo ${FRONTEND-WEBSITE}
+            if curl -s ${FRONTEND-WEBSITE} | grep "Welcome"
             then
-              return 1
+              exit 1
             else
-              return 1
+              exit 1
             fi
       - destroy-environment
       - revert-migrations  
@@ -462,7 +463,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
